DROP TABLE IF EXISTS posts;
DROP TABLE IF EXISTS announcements;

CREATE TABLE posts (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    title TEXT NOT NULL,
    content TEXT NOT NULL,
    created_at DATETIME DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE announcements (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    announcement TEXT NOT NULL,
    created_at DATETIME DEFAULT CURRENT_TIMESTAMP
)